# Generated by Django 5.1.2 on 2024-10-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('imagem', models.ImageField(upload_to='imagens/')),
                ('link', models.URLField()),
                ('icone_tipo', models.CharField(max_length=50)),
            ],
        ),
    ]
