# Generated by Django 5.1.2 on 2024-10-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoFeed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='icone_tipo',
        ),
        migrations.AddField(
            model_name='noticia',
            name='icone',
            field=models.CharField(default='icone-default', max_length=100),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
