# Generated by Django 5.1.2 on 2024-11-22 22:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoFeed', '0003_noticia_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-data_adicionado'], 'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
        migrations.AddField(
            model_name='noticia',
            name='data_adicionado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='noticia',
            name='duracao',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='icone',
            field=models.CharField(default='locationIcon', max_length=100),
        ),
    ]
