# Generated by Django 5.1.1 on 2024-09-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0005_alter_footballclubs_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footballclubs',
            old_name='name',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='footballclubs',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='footballclubs',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='footballclubs',
            name='city',
        ),
        migrations.RemoveField(
            model_name='footballclubs',
            name='country',
        ),
        migrations.RemoveField(
            model_name='footballclubs',
            name='stadium',
        ),
        migrations.RemoveField(
            model_name='footballclubs',
            name='zipcode',
        ),
        migrations.AlterField(
            model_name='footballclubs',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
